name: studiograenitz
favicon: null
layout_spectrum: 0.03605
typography_spectrum: 0.89894
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4e4c4d'
    - '#ffffff'
    - '#e36f46'
    - '#000000'
    - '#8b8c88'
  brandStrength: 0.25
  lightness: 0.9492876755539328
  saturation: 0.28232362447306514
  rhythmicContrast: 0
purpose: []
