name: studiograenitz
favicon: null
layout_spectrum: 0.39530662330798805
typography_spectrum: 0.45949072972871363
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3328993353061378
  lightness: 0.9492876755539328
  saturation: 0.28232362447306514
  rhythmicContrast: 0.0635998125653714
purpose: []
