name: studiograenitz
favicon: null
layout_spectrum: 0.28709
typography_spectrum: 0.89894
title: Studio Graenitz Inc. ... drinking tea and making art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#c5c9d0'
    - '#787b87'
    - '#444444'
  brandStrength: 0.1875
  lightness: 0.9375
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
